#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PaySplit.Droid.Resource", IsApplication=true)]

namespace PaySplit.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int categories_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int accentColor = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int actionBarBackgroundColor = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int actionBarTextColor = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int background = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int statusBarBackgroundColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addbill = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int big_card = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Rounded = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090035
			public const int CategoryName = 2131296309;
			
			// aapt resource value: 0x7f090006
			public const int Details_BillAmount = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int Details_BillAmount_Edit = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int Details_BillCategory = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int Details_BillCategory_Edit = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int Details_BillDesc = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int Details_BillDesc_Edit = 2131296275;
			
			// aapt resource value: 0x7f090002
			public const int Details_BillName = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int Details_BillName_Edit = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int Details_Date = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int Details_Date_Edit = 2131296267;
			
			// aapt resource value: 0x7f090016
			public const int Details_EditButton = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int Details_SaveButton = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int Details_Updated = 2131296280;
			
			// aapt resource value: 0x7f090004
			public const int Details_amountLabel = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Details_amount_switcher = 2131296261;
			
			// aapt resource value: 0x7f090015
			public const int Details_button_switcher = 2131296277;
			
			// aapt resource value: 0x7f09000c
			public const int Details_categoryLabel = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int Details_category_switcher = 2131296269;
			
			// aapt resource value: 0x7f090008
			public const int Details_dateLabel = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int Details_date_switcher = 2131296265;
			
			// aapt resource value: 0x7f090011
			public const int Details_desc_switcher = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int Details_descriptionLabel = 2131296272;
			
			// aapt resource value: 0x7f090014
			public const int Details_imageView = 2131296276;
			
			// aapt resource value: 0x7f090000
			public const int Details_nameLabel = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Details_name_switcher = 2131296257;
			
			// aapt resource value: 0x7f090029
			public const int Main_AddEntry = 2131296297;
			
			// aapt resource value: 0x7f09002b
			public const int Main_Categoriesbtn = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int Main_DelBtn = 2131296301;
			
			// aapt resource value: 0x7f09002a
			public const int Main_Viewbtn = 2131296298;
			
			// aapt resource value: 0x7f09002e
			public const int Main_imageView = 2131296302;
			
			// aapt resource value: 0x7f09002c
			public const int Main_picture = 2131296300;
			
			// aapt resource value: 0x7f090030
			public const int NoResults = 2131296304;
			
			// aapt resource value: 0x7f09002f
			public const int NoResultsImage = 2131296303;
			
			// aapt resource value: 0x7f090031
			public const int View_ListView = 2131296305;
			
			// aapt resource value: 0x7f09001c
			public const int amount = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int amountLabel = 2131296283;
			
			// aapt resource value: 0x7f090034
			public const int billCategory = 2131296308;
			
			// aapt resource value: 0x7f090033
			public const int billDescription = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int billTitle = 2131296306;
			
			// aapt resource value: 0x7f090028
			public const int cancel = 2131296296;
			
			// aapt resource value: 0x7f09001f
			public const int categoryLabel = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int category_spinner = 2131296288;
			
			// aapt resource value: 0x7f090024
			public const int date = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int datePicker = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int description = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int descriptionLabel = 2131296285;
			
			// aapt resource value: 0x7f090036
			public const int listview_background_shape = 2131296310;
			
			// aapt resource value: 0x7f09001a
			public const int name = 2131296282;
			
			// aapt resource value: 0x7f090019
			public const int nameLabel = 2131296281;
			
			// aapt resource value: 0x7f090022
			public const int peopleAmount = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int peopleLable = 2131296289;
			
			// aapt resource value: 0x7f090025
			public const int picture = 2131296293;
			
			// aapt resource value: 0x7f090027
			public const int save = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int takePic = 2131296294;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int BillDetails = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CreateBillEntry = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main_ListView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ViewBills = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ViewCategory = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int new_icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int category_prompt = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme_ActionBarStyle = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
