#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PaySplit.Droid.Resource", IsApplication=true)]

namespace PaySplit.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int categories_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addbill = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int big_card = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rectangle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Rounded = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070035
			public const int CategoryName = 2131165237;
			
			// aapt resource value: 0x7f070006
			public const int Details_BillAmount = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Details_BillAmount_Edit = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int Details_BillCategory = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Details_BillCategory_Edit = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int Details_BillDesc = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int Details_BillDesc_Edit = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int Details_BillName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Details_BillName_Edit = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int Details_Date = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Details_Date_Edit = 2131165195;
			
			// aapt resource value: 0x7f070016
			public const int Details_EditButton = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int Details_SaveButton = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int Details_Updated = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int Details_amountLabel = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Details_amount_switcher = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int Details_button_switcher = 2131165205;
			
			// aapt resource value: 0x7f07000c
			public const int Details_categoryLabel = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Details_category_switcher = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int Details_dateLabel = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int Details_date_switcher = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int Details_desc_switcher = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int Details_descriptionLabel = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int Details_imageView = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int Details_nameLabel = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Details_name_switcher = 2131165185;
			
			// aapt resource value: 0x7f070029
			public const int Main_AddEntry = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int Main_Categoriesbtn = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int Main_DelBtn = 2131165229;
			
			// aapt resource value: 0x7f07002a
			public const int Main_Viewbtn = 2131165226;
			
			// aapt resource value: 0x7f07002e
			public const int Main_imageView = 2131165230;
			
			// aapt resource value: 0x7f07002c
			public const int Main_picture = 2131165228;
			
			// aapt resource value: 0x7f070030
			public const int NoResults = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int NoResultsImage = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int View_ListView = 2131165233;
			
			// aapt resource value: 0x7f07001c
			public const int amount = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int amountLabel = 2131165211;
			
			// aapt resource value: 0x7f070034
			public const int billCategory = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int billDescription = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int billTitle = 2131165234;
			
			// aapt resource value: 0x7f070028
			public const int cancel = 2131165224;
			
			// aapt resource value: 0x7f07001f
			public const int categoryLabel = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int category_spinner = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int date = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int datePicker = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int description = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int descriptionLabel = 2131165213;
			
			// aapt resource value: 0x7f070036
			public const int listview_background_shape = 2131165238;
			
			// aapt resource value: 0x7f07001a
			public const int name = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int nameLabel = 2131165209;
			
			// aapt resource value: 0x7f070022
			public const int peopleAmount = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int peopleLable = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int picture = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int save = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int takePic = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int BillDetails = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CreateBillEntry = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main_ListView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ViewBills = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ViewCategory = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int new_icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int category_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
