#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PaySplit.Droid.Resource", IsApplication=true)]

namespace PaySplit.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Rounded = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int Details_BillAmount = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Details_BillDesc = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int Details_BillName = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int Details_CreatedOn = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int Details_Owner = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Details_Updated = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int Main_AddEntry = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int Main_DelBtn = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int Main_Viewbtn = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int Main_imageView = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int Main_picture = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int View_BillEntry = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int View_ListView = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int amount = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int amountLabel = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int cancel = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int category = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int categoryLabel = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int description = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int descriptionLabel = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int name = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int nameLabel = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int numPeople = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int peopleLable = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int pickCat = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int pickPeople = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int picture = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int save = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int takePic = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int BillDetails = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CreateBillEntry = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ViewBills = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ViewBills_ListView = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int new_icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
